// Phase 1 placeholder seed data - just enough real players to prove the
// full pipeline (seed -> MongoDB -> API -> client) works end-to-end.
// Curating the full ~40-60 player pool with carefully considered ratings
// is Phase 2's job, not this one.
export const playersSeedData = [
  {
    name: "Roger Federer",
    slug: "roger-federer",
    country: "Switzerland",
    handedness: "right",
    heightCm: 185,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 97,
      backhand: 88,
      serve: 92,
      return: 85,
      volley: 96,
      movement: 90,
      power: 82,
      mentalToughness: 90,
    },
    flavorText: {
      forehand: "One of the most elegant and lethal forehands the sport has seen.",
      volley: "Surgical touch at net, a throwback to serve-and-volley eras.",
    },
    bio: "Swiss all-time great known for effortless shot-making and net play.",
  },
  {
    name: "Rafael Nadal",
    slug: "rafael-nadal",
    country: "Spain",
    handedness: "left",
    heightCm: 185,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 96,
      backhand: 87,
      serve: 84,
      return: 89,
      volley: 78,
      movement: 97,
      power: 90,
      mentalToughness: 98,
    },
    flavorText: {
      movement: "Relentless court coverage, especially on clay.",
      mentalToughness: "Famously unbreakable competitor in tight matches.",
    },
    bio: "Spanish legend, the most dominant clay-court player in history.",
  },
  {
    name: "John Isner",
    slug: "john-isner",
    country: "United States",
    handedness: "right",
    heightCm: 208,
    careerStatus: "retired",
    tier: "current",
    attributes: {
      forehand: 72,
      backhand: 65,
      serve: 99,
      return: 55,
      volley: 68,
      movement: 58,
      power: 88,
      mentalToughness: 70,
    },
    flavorText: {
      serve: "One of the biggest serves ever recorded, a true ace machine.",
      movement: "Limited court coverage due to his sheer size.",
    },
    bio: "American giant famous for one of the most dominant serves in tennis history.",
  },
  {
    name: "Novak Djokovic",
    slug: "novak-djokovic",
    country: "Serbia",
    handedness: "right",
    heightCm: 188,
    careerStatus: "active",
    tier: "legend",
    attributes: {
      forehand: 91,
      backhand: 96,
      serve: 88,
      return: 97,
      volley: 80,
      movement: 96,
      power: 85,
      mentalToughness: 97,
    },
    flavorText: {
      return: "Widely regarded as the best returner of serve of all time.",
      backhand: "A rock-solid two-handed backhand that rarely breaks down.",
    },
    bio: "Serbian great known for elite defense, return of serve, and mental resilience.",
  },
  {
    name: "Gael Monfils",
    slug: "gael-monfils",
    country: "France",
    handedness: "right",
    heightCm: 193,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 75,
      serve: 78,
      return: 72,
      volley: 74,
      movement: 95,
      power: 80,
      mentalToughness: 65,
    },
    flavorText: {
      movement: "Freakish athleticism and speed rarely seen on tour.",
      mentalToughness: "Prone to lapses in focus during long matches.",
    },
    bio: "French athlete known for spectacular movement and highlight-reel points.",
  },
];
