// Phase 2 player reference database: 50 real ATP players spanning the
// open era to today, each rated across the 8 MVP attributes. See
// RATINGS_METHODOLOGY.md (same folder) for the full rubric this was
// drafted against - in short: ratings are informed, defensible
// approximations based on well-established career reputation, not live
// statistics, calibrated so an average tour pro sits ~65-70 and an
// all-time-best-at-that-skill sits 98-99.
//
// Composition: 30 legends/all-time greats, 40 current pros (15 from the
// original Phase 2 roster plus 25 added later to deepen the wheel's
// current-tour representation - including recent breakouts like Fonseca
// and Mensik), and 5 deliberately lower/mixed-tier players whose games
// have a sharp, well-known strength/weakness split (Isner, Monfils,
// Karlovic, Paire, Kyrgios) - these keep the pool from clustering near
// the top of the scale, which matters for real archetype variance (see
// Phase 0 design doc's balancing notes).
//
// Career simulation (career.js) only ever draws real-player Slam
// opponents from careerStatus: "active" players - i.e. this current-pro
// depth is exactly what makes that simulation meaningful.
export const playersSeedData = [
  // --- Legends / all-time greats (30) ---
  {
    name: "Roger Federer",
    slug: "roger-federer",
    country: "Switzerland",
    handedness: "right",
    heightCm: 185,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 101,
      backhand: 88,
      serve: 92,
      return: 85,
      volley: 96,
      movement: 90,
      power: 82,
      mentalToughness: 90,
    },
    flavorText: {
      forehand:
        "Widely considered the single greatest forehand the sport has ever produced - off the charts.",
      volley: "Surgical touch at net, a throwback to serve-and-volley eras.",
    },
    bio: "Swiss all-time great known for effortless shot-making and net play.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/425.png",
  },
  {
    name: "Rafael Nadal",
    slug: "rafael-nadal",
    country: "Spain",
    handedness: "left",
    heightCm: 185,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 96,
      backhand: 87,
      serve: 84,
      return: 89,
      volley: 78,
      movement: 97,
      power: 90,
      mentalToughness: 104,
    },
    flavorText: {
      movement: "Relentless court coverage, especially on clay.",
      mentalToughness:
        "The most mentally unbreakable competitor the sport has seen - off the charts.",
    },
    bio: "Spanish legend, the most dominant clay-court player in history.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/261.png",
  },
  {
    name: "Novak Djokovic",
    slug: "novak-djokovic",
    country: "Serbia",
    handedness: "right",
    heightCm: 188,
    careerStatus: "active",
    tier: "legend",
    attributes: {
      forehand: 91,
      backhand: 96,
      serve: 88,
      return: 102,
      volley: 80,
      movement: 96,
      power: 85,
      mentalToughness: 97,
    },
    flavorText: {
      return: "The greatest returner of serve the sport has ever seen - off the charts.",
      backhand: "A rock-solid two-handed backhand that rarely breaks down.",
    },
    bio: "Serbian great known for elite defense, return of serve, and mental resilience.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/296.png",
  },
  {
    name: "Pete Sampras",
    slug: "pete-sampras",
    country: "United States",
    handedness: "right",
    heightCm: 185,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 88,
      backhand: 75,
      serve: 103,
      return: 68,
      volley: 95,
      movement: 82,
      power: 88,
      mentalToughness: 92,
    },
    flavorText: {
      serve: "Arguably the greatest serve of all time on any surface - off the charts.",
      volley: "Textbook serve-and-volley technique.",
    },
    bio: "American serve-and-volley great, 14 Grand Slams and dominant on grass.",
  },
  {
    name: "Andre Agassi",
    slug: "andre-agassi",
    country: "United States",
    handedness: "right",
    heightCm: 180,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 92,
      backhand: 90,
      serve: 78,
      return: 100,
      volley: 70,
      movement: 85,
      power: 87,
      mentalToughness: 88,
    },
    flavorText: {
      return:
        "Legendary return of serve that redefined aggressive returning - off the charts.",
      backhand: "Flat, piercing two-handed backhand.",
    },
    bio: "American baseline great known for taking the ball early and an elite return.",
  },
  {
    name: "Rod Laver",
    slug: "rod-laver",
    country: "Australia",
    handedness: "left",
    heightCm: 173,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 90,
      backhand: 85,
      serve: 82,
      return: 80,
      volley: 90,
      movement: 88,
      power: 78,
      mentalToughness: 93,
    },
    flavorText: {
      mentalToughness:
        "Won the calendar Grand Slam twice, unmatched consistency at the top.",
    },
    bio: "Australian great, the only player to complete the calendar Grand Slam twice.",
  },
  {
    name: "Bjorn Borg",
    slug: "bjorn-borg",
    country: "Sweden",
    handedness: "right",
    heightCm: 180,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 88,
      backhand: 87,
      serve: 78,
      return: 85,
      volley: 72,
      movement: 92,
      power: 80,
      mentalToughness: 95,
    },
    flavorText: {
      mentalToughness:
        "Nicknamed 'Ice Borg' for his unshakable composure under pressure.",
      movement: "Tireless baseline coverage.",
    },
    bio: "Swedish baseline great famed for topspin-heavy groundstrokes and icy composure.",
  },
  {
    name: "John McEnroe",
    slug: "john-mcenroe",
    country: "United States",
    handedness: "left",
    heightCm: 180,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 80,
      backhand: 84,
      serve: 85,
      return: 82,
      volley: 101,
      movement: 83,
      power: 65,
      mentalToughness: 80,
    },
    flavorText: {
      volley: "The best hands and touch at net the sport has ever seen - off the charts.",
    },
    bio: "American serve-and-volley genius with the greatest touch of his generation.",
  },
  {
    name: "Ivan Lendl",
    slug: "ivan-lendl",
    country: "Czechoslovakia",
    handedness: "right",
    heightCm: 188,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 92,
      backhand: 84,
      serve: 85,
      return: 78,
      volley: 68,
      movement: 80,
      power: 88,
      mentalToughness: 87,
    },
    flavorText: {
      forehand: "Powerful, heavy topspin forehand that reshaped baseline tennis.",
    },
    bio: "Dominant baseline power player who pioneered modern fitness-focused training.",
  },
  {
    name: "Jimmy Connors",
    slug: "jimmy-connors",
    country: "United States",
    handedness: "left",
    heightCm: 178,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 85,
      backhand: 90,
      serve: 75,
      return: 88,
      volley: 75,
      movement: 87,
      power: 82,
      mentalToughness: 90,
    },
    flavorText: {
      mentalToughness: "Fought for every point with unmatched competitive fire.",
    },
    bio: "Relentless competitor known for his flat two-handed backhand and fighting spirit.",
  },
  {
    name: "Boris Becker",
    slug: "boris-becker",
    country: "Germany",
    handedness: "right",
    heightCm: 190,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 83,
      backhand: 78,
      serve: 93,
      return: 72,
      volley: 88,
      movement: 78,
      power: 87,
      mentalToughness: 85,
    },
    flavorText: {
      serve: "Explosive serve that powered a teenage Wimbledon title in 1985.",
    },
    bio: "German serve-and-volley powerhouse, youngest-ever Wimbledon champion at 17.",
  },
  {
    name: "Stefan Edberg",
    slug: "stefan-edberg",
    country: "Sweden",
    handedness: "right",
    heightCm: 188,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 80,
      backhand: 82,
      serve: 87,
      return: 75,
      volley: 96,
      movement: 85,
      power: 75,
      mentalToughness: 86,
    },
    flavorText: {
      volley: "Among the smoothest, most elegant volleyers the game has seen.",
    },
    bio: "Elegant Swedish serve-and-volleyer with exceptional net skills.",
  },
  {
    name: "Andy Murray",
    slug: "andy-murray",
    country: "United Kingdom",
    handedness: "right",
    heightCm: 191,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 83,
      backhand: 86,
      serve: 82,
      return: 90,
      volley: 78,
      movement: 93,
      power: 78,
      mentalToughness: 88,
    },
    flavorText: {
      movement:
        "Elite defensive counterpuncher who covers the court as well as anyone of his era.",
    },
    bio: "British counterpuncher renowned for elite defense and tactical intelligence.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/235.png",
  },
  {
    name: "Stan Wawrinka",
    slug: "stan-wawrinka",
    country: "Switzerland",
    handedness: "right",
    heightCm: 183,
    careerStatus: "active",
    tier: "legend",
    attributes: {
      forehand: 82,
      backhand: 95,
      serve: 84,
      return: 74,
      volley: 70,
      movement: 75,
      power: 90,
      mentalToughness: 84,
    },
    flavorText: {
      backhand: "One of the most devastating one-handed backhands in tennis history.",
    },
    bio: "Swiss three-time Slam champion famous for his one-handed backhand.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/264.png",
  },
  {
    name: "Juan Martin del Potro",
    slug: "juan-martin-del-potro",
    country: "Argentina",
    handedness: "right",
    heightCm: 198,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 93,
      backhand: 75,
      serve: 88,
      return: 72,
      volley: 65,
      movement: 70,
      power: 95,
      mentalToughness: 85,
    },
    flavorText: {
      forehand: "One of the most devastating forehands in tennis history.",
      power: "Combined immense height and racquet-head speed for crushing power.",
    },
    bio: "Argentine power-hitter and 2009 US Open champion.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/284.png",
  },
  {
    name: "Lleyton Hewitt",
    slug: "lleyton-hewitt",
    country: "Australia",
    handedness: "right",
    heightCm: 180,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 80,
      backhand: 82,
      serve: 72,
      return: 88,
      volley: 72,
      movement: 92,
      power: 70,
      mentalToughness: 90,
    },
    flavorText: {
      mentalToughness: "'C'mon!' - one of the fiercest competitors of his generation.",
    },
    bio: "Relentless Australian counterpuncher and former world No. 1.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/306.png",
  },
  {
    name: "Gustavo Kuerten",
    slug: "gustavo-kuerten",
    country: "Brazil",
    handedness: "right",
    heightCm: 190,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 90,
      backhand: 85,
      serve: 78,
      return: 70,
      volley: 68,
      movement: 82,
      power: 82,
      mentalToughness: 84,
    },
    flavorText: {
      forehand: "Flowing, high-topspin forehand that dominated on clay.",
    },
    bio: "Brazilian clay-court virtuoso, three-time French Open champion.",
  },
  {
    name: "Marat Safin",
    slug: "marat-safin",
    country: "Russia",
    handedness: "right",
    heightCm: 193,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 85,
      backhand: 88,
      serve: 86,
      return: 78,
      volley: 68,
      movement: 78,
      power: 90,
      mentalToughness: 65,
    },
    flavorText: {
      mentalToughness:
        "Enormous talent undercut by famous inconsistency and frustration.",
    },
    bio: "Immensely talented Russian with two Grand Slam titles but famous volatility.",
  },
  {
    name: "Goran Ivanisevic",
    slug: "goran-ivanisevic",
    country: "Croatia",
    handedness: "left",
    heightCm: 193,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 80,
      backhand: 72,
      serve: 96,
      return: 62,
      volley: 85,
      movement: 70,
      power: 85,
      mentalToughness: 78,
    },
    flavorText: {
      serve: "One of the most fearsome left-handed serves the sport has seen.",
    },
    bio: "Croatian lefty with a huge serve, 2001 Wimbledon champion as a wildcard.",
  },
  {
    name: "Pat Rafter",
    slug: "pat-rafter",
    country: "Australia",
    handedness: "right",
    heightCm: 185,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 78,
      backhand: 76,
      serve: 85,
      return: 75,
      volley: 93,
      movement: 84,
      power: 76,
      mentalToughness: 84,
    },
    flavorText: {
      volley: "Superb net instincts, one of the last great serve-and-volley champions.",
    },
    bio: "Australian serve-and-volley specialist, back-to-back US Open champion.",
  },
  {
    name: "Thomas Muster",
    slug: "thomas-muster",
    country: "Austria",
    handedness: "left",
    heightCm: 180,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 88,
      backhand: 80,
      serve: 74,
      return: 76,
      volley: 60,
      movement: 88,
      power: 84,
      mentalToughness: 90,
    },
    flavorText: {
      mentalToughness:
        "Rebuilt his career after a near career-ending injury through sheer will.",
    },
    bio: "Austrian clay-court dominator of the mid-90s, famed for relentless work ethic.",
  },
  {
    name: "Michael Chang",
    slug: "michael-chang",
    country: "United States",
    handedness: "right",
    heightCm: 175,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 80,
      backhand: 78,
      serve: 65,
      return: 82,
      volley: 68,
      movement: 90,
      power: 65,
      mentalToughness: 88,
    },
    flavorText: {
      movement: "Blazing speed let him outlast far bigger hitters.",
    },
    bio: "Undersized American known for grit, youngest-ever French Open champion.",
  },
  {
    name: "Mats Wilander",
    slug: "mats-wilander",
    country: "Sweden",
    handedness: "right",
    heightCm: 183,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 82,
      backhand: 84,
      serve: 72,
      return: 82,
      volley: 74,
      movement: 85,
      power: 72,
      mentalToughness: 88,
    },
    flavorText: {
      mentalToughness:
        "Won Grand Slams on three different surfaces in a single season (1988).",
    },
    bio: "Swedish all-court great who won majors on clay, hard, and grass.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/1689.png",
  },
  {
    name: "Guillermo Vilas",
    slug: "guillermo-vilas",
    country: "Argentina",
    handedness: "left",
    heightCm: 180,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 85,
      backhand: 80,
      serve: 68,
      return: 76,
      volley: 62,
      movement: 86,
      power: 78,
      mentalToughness: 87,
    },
    flavorText: {
      forehand: "Heavy topspin groundstrokes that helped fuel a record win streak.",
    },
    bio: "Argentine clay-court great famed for his topspin and legendary win streak.",
  },
  {
    name: "Arthur Ashe",
    slug: "arthur-ashe",
    country: "United States",
    handedness: "right",
    heightCm: 185,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 78,
      backhand: 76,
      serve: 85,
      return: 72,
      volley: 85,
      movement: 78,
      power: 80,
      mentalToughness: 88,
    },
    flavorText: {
      mentalToughness: "Calm, tactical brilliance under the sport's biggest spotlight.",
    },
    bio: "Trailblazing American champion, first Black man to win Wimbledon and the US and Australian Opens.",
  },
  {
    name: "Ken Rosewall",
    slug: "ken-rosewall",
    country: "Australia",
    handedness: "right",
    heightCm: 170,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 78,
      backhand: 90,
      serve: 70,
      return: 80,
      volley: 88,
      movement: 82,
      power: 65,
      mentalToughness: 88,
    },
    flavorText: {
      backhand:
        "One of the most elegant and effective backhands ever, winning majors into his late 30s.",
    },
    bio: "Australian great with a legendary backhand, a major champion across four decades.",
  },
  {
    name: "Roy Emerson",
    slug: "roy-emerson",
    country: "Australia",
    handedness: "right",
    heightCm: 178,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 80,
      backhand: 76,
      serve: 80,
      return: 74,
      volley: 85,
      movement: 84,
      power: 76,
      mentalToughness: 85,
    },
    flavorText: {
      mentalToughness:
        "Held the all-time Grand Slam singles titles record for over 30 years.",
    },
    bio: "Australian all-court champion who dominated the amateur era.",
  },
  {
    name: "Yevgeny Kafelnikov",
    slug: "yevgeny-kafelnikov",
    country: "Russia",
    handedness: "right",
    heightCm: 190,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 82,
      backhand: 80,
      serve: 78,
      return: 76,
      volley: 68,
      movement: 78,
      power: 80,
      mentalToughness: 78,
    },
    flavorText: {},
    bio: "First Russian man to reach world No. 1, won majors on clay and hard courts.",
  },
  {
    name: "Carlos Moya",
    slug: "carlos-moya",
    country: "Spain",
    handedness: "right",
    heightCm: 190,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 86,
      backhand: 78,
      serve: 78,
      return: 72,
      volley: 62,
      movement: 80,
      power: 84,
      mentalToughness: 80,
    },
    flavorText: {
      forehand: "Big, flat forehand that powered him to the 1998 French Open title.",
    },
    bio: "Spanish clay specialist and former world No. 1.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/253.png",
  },
  {
    name: "Juan Carlos Ferrero",
    slug: "juan-carlos-ferrero",
    country: "Spain",
    handedness: "right",
    heightCm: 178,
    careerStatus: "legend",
    tier: "legend",
    attributes: {
      forehand: 88,
      backhand: 82,
      serve: 68,
      return: 80,
      volley: 65,
      movement: 88,
      power: 76,
      mentalToughness: 82,
    },
    flavorText: {
      movement: "Nicknamed 'The Mosquito' for his tireless court coverage.",
    },
    bio: "Spanish former world No. 1 known for relentless court coverage.",
  },

  // --- Current strong pros (15) ---
  {
    name: "Carlos Alcaraz",
    slug: "carlos-alcaraz",
    country: "Spain",
    handedness: "right",
    heightCm: 183,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 92,
      backhand: 85,
      serve: 85,
      return: 85,
      volley: 88,
      movement: 95,
      power: 87,
      mentalToughness: 88,
    },
    flavorText: {
      movement: "Explosive athleticism and court coverage rarely seen at his age.",
      volley: "Exceptional touch and drop-shot creativity for a modern power player.",
    },
    bio: "Spanish phenom and multiple Grand Slam champion known for explosive, creative shot-making.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/3782.png",
  },
  {
    name: "Jannik Sinner",
    slug: "jannik-sinner",
    country: "Italy",
    handedness: "right",
    heightCm: 191,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 92,
      backhand: 90,
      serve: 87,
      return: 88,
      volley: 72,
      movement: 88,
      power: 89,
      mentalToughness: 90,
    },
    flavorText: {
      backhand: "Devastatingly flat, early-hit two-handed backhand.",
    },
    bio: "Italian world No. 1 known for flat, relentless ball-striking off both wings.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/3623.png",
  },
  {
    name: "Daniil Medvedev",
    slug: "daniil-medvedev",
    country: "Russia",
    handedness: "right",
    heightCm: 198,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 85,
      serve: 85,
      return: 90,
      volley: 70,
      movement: 85,
      power: 78,
      mentalToughness: 87,
    },
    flavorText: {
      return:
        "Elite returner who neutralizes big servers with unusual court positioning.",
    },
    bio: "Unorthodox Russian counterpuncher known for his elite return game.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2383.png",
  },
  {
    name: "Alexander Zverev",
    slug: "alexander-zverev",
    country: "Germany",
    handedness: "right",
    heightCm: 198,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 84,
      backhand: 86,
      serve: 88,
      return: 78,
      volley: 68,
      movement: 82,
      power: 87,
      mentalToughness: 78,
    },
    flavorText: {
      serve: "Towering, powerful serve backed by elite court coverage for his size.",
    },
    bio: "German power baseliner with a massive serve and elite two-handed backhand.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2375.png",
  },
  {
    name: "Casper Ruud",
    slug: "casper-ruud",
    country: "Norway",
    handedness: "right",
    heightCm: 183,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 88,
      backhand: 78,
      serve: 78,
      return: 76,
      volley: 65,
      movement: 82,
      power: 82,
      mentalToughness: 84,
    },
    flavorText: {
      forehand: "Heavy, high-bouncing topspin forehand built for clay.",
    },
    bio: "Norwegian clay-court specialist and multiple Grand Slam finalist.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2989.png",
  },
  {
    name: "Holger Rune",
    slug: "holger-rune",
    country: "Denmark",
    handedness: "right",
    heightCm: 188,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 85,
      backhand: 84,
      serve: 80,
      return: 82,
      volley: 68,
      movement: 86,
      power: 82,
      mentalToughness: 76,
    },
    flavorText: {
      mentalToughness:
        "Fiery competitor whose emotions can run as hot as his shot-making.",
    },
    bio: "Young Danish talent known for aggressive baseline power and intensity.",
  },
  {
    name: "Taylor Fritz",
    slug: "taylor-fritz",
    country: "United States",
    handedness: "right",
    heightCm: 196,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 84,
      backhand: 78,
      serve: 88,
      return: 74,
      volley: 68,
      movement: 78,
      power: 86,
      mentalToughness: 80,
    },
    flavorText: {
      serve: "One of the biggest, most reliable serves on the modern tour.",
    },
    bio: "American big-serving power player and Grand Slam finalist.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2946.png",
  },
  {
    name: "Grigor Dimitrov",
    slug: "grigor-dimitrov",
    country: "Bulgaria",
    handedness: "right",
    heightCm: 191,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 88,
      serve: 80,
      return: 74,
      volley: 80,
      movement: 84,
      power: 78,
      mentalToughness: 74,
    },
    flavorText: {
      backhand: "Elegant one-handed backhand that earned him the nickname 'Baby Fed'.",
    },
    bio: "Bulgarian stylist with an elegant one-handed backhand.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/1287.png",
  },
  {
    name: "Frances Tiafoe",
    slug: "frances-tiafoe",
    country: "United States",
    handedness: "right",
    heightCm: 188,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 78,
      serve: 80,
      return: 76,
      volley: 72,
      movement: 88,
      power: 82,
      mentalToughness: 76,
    },
    flavorText: {
      movement: "Explosive athleticism that fuels his crowd-pleasing style.",
    },
    bio: "Athletic American known for flashy shot-making and crowd-pleasing energy.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2708.png",
  },
  {
    name: "Felix Auger-Aliassime",
    slug: "felix-auger-aliassime",
    country: "Canada",
    handedness: "right",
    heightCm: 193,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 80,
      serve: 87,
      return: 74,
      volley: 74,
      movement: 82,
      power: 85,
      mentalToughness: 76,
    },
    flavorText: {
      serve: "Huge, athletic serve that's among the tour's most consistent weapons.",
    },
    bio: "Canadian power player with one of the tour's biggest serves and forehands.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/3209.png",
  },
  {
    name: "Andrey Rublev",
    slug: "andrey-rublev",
    country: "Russia",
    handedness: "right",
    heightCm: 188,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 90,
      backhand: 82,
      serve: 80,
      return: 76,
      volley: 62,
      movement: 78,
      power: 88,
      mentalToughness: 72,
    },
    flavorText: {
      forehand: "Blistering, flat forehand struck with maximum effort on every ball.",
      mentalToughness: "Passionate, occasionally combustible on-court emotion.",
    },
    bio: "Russian power baseliner known for one of the tour's biggest forehands.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2642.png",
  },
  {
    name: "Hubert Hurkacz",
    slug: "hubert-hurkacz",
    country: "Poland",
    handedness: "right",
    heightCm: 196,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 78,
      backhand: 76,
      serve: 90,
      return: 68,
      volley: 78,
      movement: 76,
      power: 82,
      mentalToughness: 78,
    },
    flavorText: {
      serve: "One of the most efficient, high-percentage serves in the modern game.",
    },
    bio: "Polish big-server known for one of the most efficient service games on tour.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2726.png",
  },
  {
    name: "Tommy Paul",
    slug: "tommy-paul",
    country: "United States",
    handedness: "right",
    heightCm: 185,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 80,
      serve: 76,
      return: 80,
      volley: 74,
      movement: 88,
      power: 76,
      mentalToughness: 80,
    },
    flavorText: {
      movement: "Quick, well-rounded movement that anchors a versatile all-court game.",
    },
    bio: "American all-courter known for solid movement and counterpunching instincts.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2964.png",
  },
  {
    name: "Ben Shelton",
    slug: "ben-shelton",
    country: "United States",
    handedness: "left",
    heightCm: 193,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 84,
      backhand: 74,
      serve: 92,
      return: 68,
      volley: 76,
      movement: 82,
      power: 88,
      mentalToughness: 76,
    },
    flavorText: {
      serve: "Explosive left-handed serve that's among the fastest on tour.",
    },
    bio: "Explosive American lefty with a huge serve and fearless attacking style.",
  },
  {
    name: "Stefanos Tsitsipas",
    slug: "stefanos-tsitsipas",
    country: "Greece",
    handedness: "right",
    heightCm: 193,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 85,
      backhand: 78,
      serve: 83,
      return: 76,
      volley: 78,
      movement: 84,
      power: 82,
      mentalToughness: 78,
    },
    flavorText: {
      backhand: "Stylish one-handed backhand paired with an aggressive net game.",
    },
    bio: "Greek all-courter with an elegant one-handed backhand and aggressive net game.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2869.png",
  },

  // --- Variance / sharp tradeoff players (5) ---
  // These deliberately have a real, well-known weakness alongside a real
  // strength, so the wheel isn't only offering superstar-everywhere cards.
  {
    name: "John Isner",
    slug: "john-isner",
    country: "United States",
    handedness: "right",
    heightCm: 208,
    careerStatus: "retired",
    tier: "current",
    attributes: {
      forehand: 72,
      backhand: 65,
      serve: 99,
      return: 55,
      volley: 68,
      movement: 58,
      power: 88,
      mentalToughness: 70,
    },
    flavorText: {
      serve: "One of the biggest serves ever recorded, a true ace machine.",
      movement: "Limited court coverage due to his sheer size.",
    },
    bio: "American giant famous for one of the most dominant serves in tennis history.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/1023.png",
  },
  {
    name: "Gael Monfils",
    slug: "gael-monfils",
    country: "France",
    handedness: "right",
    heightCm: 193,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 75,
      serve: 78,
      return: 72,
      volley: 74,
      movement: 95,
      power: 80,
      mentalToughness: 65,
    },
    flavorText: {
      movement: "Freakish athleticism and speed rarely seen on tour.",
      mentalToughness: "Prone to lapses in focus during long matches.",
    },
    bio: "French athlete known for spectacular movement and highlight-reel points.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/242.png",
  },
  {
    name: "Ivo Karlovic",
    slug: "ivo-karlovic",
    country: "Croatia",
    handedness: "right",
    heightCm: 211,
    careerStatus: "retired",
    tier: "journeyman",
    attributes: {
      forehand: 68,
      backhand: 62,
      serve: 99,
      return: 45,
      volley: 70,
      movement: 45,
      power: 80,
      mentalToughness: 68,
    },
    flavorText: {
      serve:
        "Holds the all-time ATP aces record - arguably the single biggest serve ever.",
      movement: "Elite height comes at the cost of significantly limited court coverage.",
    },
    bio: "Croatian giant who holds the all-time ATP aces record with arguably the biggest serve ever.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/233.png",
  },
  {
    name: "Benoit Paire",
    slug: "benoit-paire",
    country: "France",
    handedness: "right",
    heightCm: 196,
    careerStatus: "active",
    tier: "journeyman",
    attributes: {
      forehand: 82,
      backhand: 84,
      serve: 76,
      return: 68,
      volley: 78,
      movement: 74,
      power: 76,
      mentalToughness: 45,
    },
    flavorText: {
      mentalToughness:
        "Immense natural talent repeatedly undone by famously poor focus and consistency.",
      backhand: "Gifted, versatile shot-making unlike almost anyone else on tour.",
    },
    bio: "Talented French shot-maker whose skill is undercut by notorious inconsistency.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/1571.png",
  },
  {
    name: "Nick Kyrgios",
    slug: "nick-kyrgios",
    country: "Australia",
    handedness: "right",
    heightCm: 193,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 84,
      backhand: 76,
      serve: 93,
      return: 72,
      volley: 85,
      movement: 80,
      power: 85,
      mentalToughness: 55,
    },
    flavorText: {
      serve: "One of the biggest, most explosive serves in the modern game.",
      mentalToughness:
        "Immense talent frequently undercut by self-admitted lapses in focus.",
    },
    bio: "Enormously talented Australian with a huge serve and dazzling touch, but famously inconsistent.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/1984.png",
  },

  // --- Deeper current-tour roster (25) ---
  // Expands the current-pro pool well past the original 15, reaching
  // further into today's top 100 and including recent breakout talents
  // (Fonseca, Mensik) - added so the wheel draws from a much larger slice
  // of the actual tour, and so career simulation (which only ever draws
  // real-player Slam opponents from careerStatus: "active" players) has a
  // meaningfully deep field to pull from.
  {
    name: "Jack Draper",
    slug: "jack-draper",
    country: "United Kingdom",
    handedness: "left",
    heightCm: 193,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 84,
      backhand: 78,
      serve: 90,
      return: 74,
      volley: 70,
      movement: 78,
      power: 88,
      mentalToughness: 78,
    },
    flavorText: {
      serve:
        "A huge left-handed serve that's become one of the tour's most feared weapons.",
    },
    bio: "British powerhouse with a massive lefty serve and forehand, a rapid late-blooming riser.",
  },
  {
    name: "Joao Fonseca",
    slug: "joao-fonseca",
    country: "Brazil",
    handedness: "right",
    heightCm: 188,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 88,
      backhand: 76,
      serve: 84,
      return: 72,
      volley: 66,
      movement: 80,
      power: 85,
      mentalToughness: 74,
    },
    flavorText: {
      forehand:
        "An explosive, whip-fast forehand that's already among the tour's biggest weapons.",
    },
    bio: "Brazilian teenage sensation who broke into the tour's elite with fearless, all-out shot-making.",
  },
  {
    name: "Jakub Mensik",
    slug: "jakub-mensik",
    country: "Czech Republic",
    handedness: "right",
    heightCm: 196,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 78,
      serve: 89,
      return: 72,
      volley: 70,
      movement: 78,
      power: 86,
      mentalToughness: 77,
    },
    flavorText: {
      serve: "A towering, precise serve that powered a shock Miami Masters title.",
    },
    bio: "Young Czech big-server who announced himself with a Masters 1000 title.",
  },
  {
    name: "Alex de Minaur",
    slug: "alex-de-minaur",
    country: "Australia",
    handedness: "right",
    heightCm: 183,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 78,
      backhand: 76,
      serve: 74,
      return: 80,
      volley: 72,
      movement: 94,
      power: 68,
      mentalToughness: 82,
    },
    flavorText: {
      movement:
        "Relentless speed and retrieving that wears opponents down point after point.",
    },
    bio: "Australian counterpuncher built on elite court coverage and relentless competitiveness.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2651.png",
  },
  {
    name: "Lorenzo Musetti",
    slug: "lorenzo-musetti",
    country: "Italy",
    handedness: "right",
    heightCm: 185,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 80,
      backhand: 86,
      serve: 74,
      return: 74,
      volley: 76,
      movement: 82,
      power: 74,
      mentalToughness: 74,
    },
    flavorText: {
      backhand:
        "A gorgeous, versatile one-handed backhand among the most stylish on tour.",
    },
    bio: "Italian stylist with a beautiful one-handed backhand and clay-friendly all-court game.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/3764.png",
  },
  {
    name: "Sebastian Korda",
    slug: "sebastian-korda",
    country: "United States",
    handedness: "right",
    heightCm: 196,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 80,
      serve: 82,
      return: 76,
      volley: 74,
      movement: 78,
      power: 80,
      mentalToughness: 74,
    },
    flavorText: {},
    bio: "American with clean, classical ball-striking off both wings from a tennis family.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/3368.png",
  },
  {
    name: "Alexei Popyrin",
    slug: "alexei-popyrin",
    country: "Australia",
    handedness: "right",
    heightCm: 196,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 74,
      serve: 86,
      return: 68,
      volley: 68,
      movement: 74,
      power: 84,
      mentalToughness: 70,
    },
    flavorText: {},
    bio: "Big-hitting Australian capable of huge, streaky wins over the tour's best.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2862.png",
  },
  {
    name: "Jiri Lehecka",
    slug: "jiri-lehecka",
    country: "Czech Republic",
    handedness: "right",
    heightCm: 188,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 83,
      backhand: 78,
      serve: 83,
      return: 72,
      volley: 70,
      movement: 76,
      power: 85,
      mentalToughness: 75,
    },
    flavorText: {},
    bio: "Powerful young Czech aggressive baseliner with a heavy, flat ball.",
  },
  {
    name: "Arthur Fils",
    slug: "arthur-fils",
    country: "France",
    handedness: "right",
    heightCm: 185,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 85,
      backhand: 76,
      serve: 80,
      return: 72,
      volley: 70,
      movement: 82,
      power: 83,
      mentalToughness: 73,
    },
    flavorText: {},
    bio: "Explosive young French talent with a huge forehand and fearless attacking instincts.",
  },
  {
    name: "Flavio Cobolli",
    slug: "flavio-cobolli",
    country: "Italy",
    handedness: "right",
    heightCm: 185,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 79,
      backhand: 75,
      serve: 76,
      return: 74,
      volley: 70,
      movement: 82,
      power: 76,
      mentalToughness: 74,
    },
    flavorText: {},
    bio: "Athletic Italian riser comfortable grinding out long clay-court rallies.",
  },
  {
    name: "Learner Tien",
    slug: "learner-tien",
    country: "United States",
    handedness: "left",
    heightCm: 178,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 78,
      backhand: 80,
      serve: 70,
      return: 76,
      volley: 74,
      movement: 80,
      power: 68,
      mentalToughness: 76,
    },
    flavorText: {},
    bio: "Undersized American lefty who plays a crafty, high-IQ, touch-heavy game.",
  },
  {
    name: "Alex Michelsen",
    slug: "alex-michelsen",
    country: "United States",
    handedness: "right",
    heightCm: 196,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 80,
      backhand: 76,
      serve: 85,
      return: 70,
      volley: 68,
      movement: 76,
      power: 82,
      mentalToughness: 72,
    },
    flavorText: {},
    bio: "Tall American with a big, flat, first-strike game built around his serve.",
  },
  {
    name: "Francisco Cerundolo",
    slug: "francisco-cerundolo",
    country: "Argentina",
    handedness: "right",
    heightCm: 190,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 82,
      backhand: 78,
      serve: 76,
      return: 76,
      volley: 70,
      movement: 84,
      power: 78,
      mentalToughness: 78,
    },
    flavorText: {},
    bio: "Consistent Argentine clay-courter with a well-rounded, dependable baseline game.",
  },
  {
    name: "Tomas Machac",
    slug: "tomas-machac",
    country: "Czech Republic",
    handedness: "right",
    heightCm: 188,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 79,
      backhand: 77,
      serve: 79,
      return: 74,
      volley: 74,
      movement: 84,
      power: 78,
      mentalToughness: 74,
    },
    flavorText: {},
    bio: "Athletic Czech all-courter equally comfortable at net and from the baseline.",
  },
  {
    name: "Alexander Bublik",
    slug: "alexander-bublik",
    country: "Kazakhstan",
    handedness: "right",
    heightCm: 196,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 80,
      backhand: 74,
      serve: 90,
      return: 66,
      volley: 76,
      movement: 78,
      power: 82,
      mentalToughness: 58,
    },
    flavorText: {
      mentalToughness: "Capable of brilliance and self-sabotage in the same match.",
    },
    bio: "Wildly talented shot-maker whose huge serve and flair are undercut by streaky focus.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2865.png",
  },
  {
    name: "Ugo Humbert",
    slug: "ugo-humbert",
    country: "France",
    handedness: "left",
    heightCm: 188,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 80,
      backhand: 78,
      serve: 84,
      return: 72,
      volley: 74,
      movement: 80,
      power: 80,
      mentalToughness: 75,
    },
    flavorText: {},
    bio: "Clean-hitting French lefty who thrives on faster hard and grass courts.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/3085.png",
  },
  {
    name: "Denis Shapovalov",
    slug: "denis-shapovalov",
    country: "Canada",
    handedness: "left",
    heightCm: 185,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 88,
      backhand: 74,
      serve: 84,
      return: 70,
      volley: 74,
      movement: 80,
      power: 84,
      mentalToughness: 66,
    },
    flavorText: {
      forehand:
        "A huge, whippy lefty forehand capable of taking over a match in a heartbeat.",
    },
    bio: "Flashy Canadian lefty with one of the tour's biggest forehands, streaky but explosive.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2860.png",
  },
  {
    name: "Karen Khachanov",
    slug: "karen-khachanov",
    country: "Russia",
    handedness: "right",
    heightCm: 198,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 84,
      backhand: 80,
      serve: 85,
      return: 72,
      volley: 68,
      movement: 76,
      power: 88,
      mentalToughness: 76,
    },
    flavorText: {},
    bio: "Powerful Russian baseliner who can overwhelm opponents with sheer ball-striking.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2367.png",
  },
  {
    name: "Cameron Norrie",
    slug: "cameron-norrie",
    country: "United Kingdom",
    handedness: "left",
    heightCm: 185,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 76,
      backhand: 78,
      serve: 74,
      return: 78,
      volley: 68,
      movement: 86,
      power: 70,
      mentalToughness: 84,
    },
    flavorText: {
      mentalToughness:
        "A relentless grinder who wears opponents down through sheer will.",
    },
    bio: "Gritty British lefty built on fitness, consistency, and refusing to go away.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2366.png",
  },
  {
    name: "Matteo Berrettini",
    slug: "matteo-berrettini",
    country: "Italy",
    handedness: "right",
    heightCm: 196,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 88,
      backhand: 74,
      serve: 92,
      return: 66,
      volley: 76,
      movement: 70,
      power: 90,
      mentalToughness: 76,
    },
    flavorText: {
      serve: "A booming serve-forehand combination that reached a Wimbledon final.",
    },
    bio: "Powerful Italian with a huge serve and forehand, a Wimbledon finalist when healthy.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2622.png",
  },
  {
    name: "Marin Cilic",
    slug: "marin-cilic",
    country: "Croatia",
    handedness: "right",
    heightCm: 198,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 84,
      backhand: 78,
      serve: 88,
      return: 70,
      volley: 72,
      movement: 68,
      power: 86,
      mentalToughness: 80,
    },
    flavorText: {},
    bio: "Veteran Croatian Grand Slam champion still competing on the strength of a huge serve.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/464.png",
  },
  {
    name: "Corentin Moutet",
    slug: "corentin-moutet",
    country: "France",
    handedness: "left",
    heightCm: 178,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 74,
      backhand: 78,
      serve: 66,
      return: 76,
      volley: 82,
      movement: 82,
      power: 62,
      mentalToughness: 70,
    },
    flavorText: {
      volley: "Exceptional touch and creativity at net, a throwback to an earlier era.",
    },
    bio: "Crafty French lefty who relies on touch, variety, and net skills over raw power.",
  },
  {
    name: "Jaume Munar",
    slug: "jaume-munar",
    country: "Spain",
    handedness: "right",
    heightCm: 183,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 78,
      backhand: 78,
      serve: 72,
      return: 76,
      volley: 68,
      movement: 84,
      power: 72,
      mentalToughness: 80,
    },
    flavorText: {},
    bio: "Steady Spanish grinder built in the classic clay-court mold.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/2709.png",
  },
  {
    name: "Brandon Nakashima",
    slug: "brandon-nakashima",
    country: "United States",
    handedness: "right",
    heightCm: 188,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 78,
      backhand: 80,
      serve: 78,
      return: 76,
      volley: 72,
      movement: 80,
      power: 76,
      mentalToughness: 78,
    },
    flavorText: {},
    bio: "Steady, error-free young American who wins through consistency over flash.",
    imageUrl: "https://a.espncdn.com/i/headshots/tennis/players/full/3774.png",
  },
  {
    name: "Zhizhen Zhang",
    slug: "zhizhen-zhang",
    country: "China",
    handedness: "right",
    heightCm: 190,
    careerStatus: "active",
    tier: "current",
    attributes: {
      forehand: 78,
      backhand: 76,
      serve: 80,
      return: 72,
      volley: 70,
      movement: 78,
      power: 78,
      mentalToughness: 74,
    },
    flavorText: {},
    bio: "China's highest-ranked ATP player, a well-rounded modern baseliner.",
  },
];
